const UNAUTHORIZED = 'Unauthorized';
const SUPABASE_AUTH = 'SUPABASE_AUTH';
const AUTH_STRATEGY_NAME = 'AUTH_SUPABASE_JWT';
const REFRESH_STRATEGY_NAME = 'REFRESH_SUPABASE_JWT';
const SUPABASE_AUTH_REFRESH = 'SUPABASE_AUTH_REFRESH';

export {
  UNAUTHORIZED,
  SUPABASE_AUTH,
  SUPABASE_AUTH_REFRESH,
  REFRESH_STRATEGY_NAME,
  AUTH_STRATEGY_NAME,
};
